version: '2'
services:
    rabbitmq:
        image: rabbitmq:3.6.6
        tty: true

    producer:
        build: ./pyapp
        image: prodcon-pyapp:1.0
        links:
            - rabbitmq:rabbitmq
        volumes:
            - ./pyapp:/usr/src/app
        # command: python /usr/src/app/producer.py
        command: echo 1

    queue-worker:
        build: ./pyapp
        image: prodcon-pyapp:1.0
        tty: true
        links:
            - rabbitmq:rabbitmq
        volumes:
            - ./pyapp:/usr/src/app
        command: python /usr/src/app/consumer_queue.py queue

    queue-ack-worker:
        build: ./pyapp
        image: prodcon-pyapp:1.0
        tty: true
        links:
            - rabbitmq:rabbitmq
        volumes:
            - ./pyapp:/usr/src/app
        command: python /usr/src/app/consumer_queue.py queue-ack

    rpc-worker:
        build: ./pyapp
        image: prodcon-pyapp:1.0
        tty: true
        links:
            - rabbitmq:rabbitmq
        volumes:
            - ./pyapp:/usr/src/app
        command: python /usr/src/app/consumer_queue.py rpc

    exchange-worker:
        build: ./pyapp
        image: prodcon-pyapp:1.0
        tty: true
        links:
            - rabbitmq:rabbitmq
        volumes:
            - ./pyapp:/usr/src/app
        command: python /usr/src/app/consumer_exchange.py

    direct-exchange-worker-a:
        build: ./pyapp
        image: prodcon-pyapp:1.0
        tty: true
        links:
            - rabbitmq:rabbitmq
        volumes:
            - ./pyapp:/usr/src/app
        command: python /usr/src/app/consumer_direct_exchange.py a

    direct-exchange-worker-b:
        build: ./pyapp
        image: prodcon-pyapp:1.0
        tty: true
        links:
            - rabbitmq:rabbitmq
        volumes:
            - ./pyapp:/usr/src/app
        command: python /usr/src/app/consumer_direct_exchange.py b

    direct-exchange-worker-c:
        build: ./pyapp
        image: prodcon-pyapp:1.0
        tty: true
        links:
            - rabbitmq:rabbitmq
        volumes:
            - ./pyapp:/usr/src/app
        command: python /usr/src/app/consumer_direct_exchange.py c

    direct-exchange-worker-any:
        build: ./pyapp
        image: prodcon-pyapp:1.0
        tty: true
        links:
            - rabbitmq:rabbitmq
        volumes:
            - ./pyapp:/usr/src/app
        command: python /usr/src/app/consumer_direct_exchange.py any

    topic-exchange-worker-any:
        build: ./pyapp
        image: prodcon-pyapp:1.0
        tty: true
        links:
            - rabbitmq:rabbitmq
        volumes:
            - ./pyapp:/usr/src/app
        command: python /usr/src/app/consumer_topic_exchange.py any

    topic-exchange-worker-kern:
        build: ./pyapp
        image: prodcon-pyapp:1.0
        tty: true
        links:
            - rabbitmq:rabbitmq
        volumes:
            - ./pyapp:/usr/src/app
        command: python /usr/src/app/consumer_topic_exchange.py kern

    topic-exchange-worker-critical:
        build: ./pyapp
        image: prodcon-pyapp:1.0
        tty: true
        links:
            - rabbitmq:rabbitmq
        volumes:
            - ./pyapp:/usr/src/app
        command: python /usr/src/app/consumer_topic_exchange.py critical

    topic-exchange-worker-kerncritical:
        build: ./pyapp
        image: prodcon-pyapp:1.0
        tty: true
        links:
            - rabbitmq:rabbitmq
        volumes:
            - ./pyapp:/usr/src/app
        command: python /usr/src/app/consumer_topic_exchange.py kerncritical
