version: '2'
services:

    rabbitmq:
        image: rabbitmq:3.6.6
        tty: true

    web:
        build: ./web
        image: prodcon-web:1.0
        volumes:
            - ./web:/usr/src/app
        ports:
            - 8888:8888
        command: python /usr/src/app/app.py && bash -l

    producer:
        build: ./pyapp
        image: prodcon-pyapp:1.0
        links:
            - rabbitmq:rabbitmq
        volumes:
            - ./pyapp:/usr/src/app
        command: python /usr/src/app/producer.py

    queue-worker:
        build: ./pyapp
        image: prodcon-pyapp:1.0
        tty: true
        links:
            - rabbitmq:rabbitmq
        volumes:
            - ./pyapp:/usr/src/app
        command: python /usr/src/app/consumer_queue.py queue

    queue-ack-worker:
        build: ./pyapp
        image: prodcon-pyapp:1.0
        tty: true
        links:
            - rabbitmq:rabbitmq
        volumes:
            - ./pyapp:/usr/src/app
        command: python /usr/src/app/consumer_queue.py queue-ack

    exchange-worker:
        build: ./pyapp
        image: prodcon-pyapp:1.0
        tty: true
        links:
            - rabbitmq:rabbitmq
        volumes:
            - ./pyapp:/usr/src/app
        command: python /usr/src/app/consumer_exchange.py

