version: '2'
services:
    rabbitmq:
        image: rabbitmq:3.6.6
        tty: true

    producer:
        build: ./pyapp
        image: prodcon-pyapp:1.0
        tty: true
        links:
            - rabbitmq:rabbitmq
        volumes:
            - ./pyapp:/usr/src/app
        command: python /usr/src/app/app.py

    worker:
        build: ./pyapp
        image: prodcon-pyapp:1.0
        tty: true
        links:
            - rabbitmq:rabbitmq
        volumes:
            - ./pyapp:/usr/src/app
        command: python /usr/src/app/consumer.py
